#cloud-config
users:
- name: user
  ssh_authorized_keys:
  - 'ssh-ed25519 YOUR-SSH-KEY-HERE'
  shell: /bin/bash
  sudo: "ALL=(ALL) NOPASSWD:ALL"
package_update: true
packages:
- bash-completion
- curl
- dnsutils
- git
- gron
- htop
- jq
- less
- psmisc
- rsync
- socat
- tig
- unattended-upgrades
- unzip
- vim-nox
- wget
- zip
# - docker.io
# - docker-compose
