# Models based on https://aider.chat/docs/leaderboards/ at 2025-04-15
alias:
  # few free that actually works
  - "free:openrouter/mistralai/devstral-small-2505:free"
  #- "free:openrouter/deepseek/deepseek-chat:free"
  # Non-free
  - "devstral:openrouter/mistralai/devstral-small" # USD 0.12
  - "gemma:openrouter/google/gemma-3-27b-it" # USD 0.2
  - "qwen:openrouter/qwen/qwen-3-coder" # USD 0.3
  - "gpt:openrouter/openai/gpt-4o-mini" # USD 0.6
  - "llama:openrouter/meta-llama/llama-4-maverick" # USD 0.6
  - "deepseek:openrouter/deepseek/deepseek-chat-v3-0324" # USD 1.5
  - "devstral-big:openrouter/mistralai/devstral-medium" # USD 2.0
  - "gemini:openrouter/google/gemini-2.5-flash" # USD 2.5
  - "claude:openrouter/anthropic/claude-3.5-haiku" # USD 4
  - "o3:openrouter/openai/o3-mini-high" # USD 4.40
  - "o4:openrouter/openai/o4-mini-high" # USD 4.40
  - "gemini-big:openrouter/google/gemini-2.5-pro-preview" # USD 10-15
  - "claude-big:openrouter/anthropic/claude-sonnet-4" # USD 15

# Default model (possibly alias):
model: free

# Other global life quality settings:
vim: true
dark-mode: true
watch-files: true
analytics-disable: true

# Configure API key(s) here:
api-key:
  - openrouter=XXX
  - gemini=XXX

# Local config:
