# Models based on https://aider.chat/docs/leaderboards/ at 2025-04-15
alias:
  # few free that actually works
  - "free:openrouter/meta-llama/llama-4-maverick:free"
  #- "free:openrouter/meta-llama/llama-4-scout:free"
  #- "free:openrouter/qwen/qwen2.5-vl-32b-instruct:free"
  #- "free:openrouter/qwen/qwen2.5-vl-72b-instruct:free"
  #- "free:openrouter/mistralai/mistral-7b-instruct:free"
  # Non-free
  - "qwen:openrouter/qwen/qwen-2.5-coder-32b-instruct" # USD 0.15
  - "gemma:openrouter/google/gemma-3-27b-it" # USD 0.2
  - "gemini:openrouter/google/gemini-2.0-flash-001" # USD 0.4
  - "4o:openrouter/openai/gpt-4o-mini" # USD 0.6
  - "llama4:openrouter/meta-llama/llama-4-maverick" # USD 0.6
  - "deepseek:openrouter/deepseek/deepseek-chat-v3-0324" # USD 1.5
  - "claude:openrouter/anthropic/claude-3.5-haiku" # USD 4
  - "o3:openrouter/openai/o3-mini-high" # USD 4.40
  - "o4:openrouter/openai/o4-mini-high" # USD 4.40
  - "gemini-big:openrouter/google/gemini-2.5-pro-preview" # USD 10-15
  - "claude-big:openrouter/anthropic/claude-3.7-sonnet" # USD 15

# Default model (possibly alias):
model: free

# Other global life quality settings:
vim: true
dark-mode: true
watch-files: true
analytics-disable: true

# Configure API key(s) here:
api-key:
  - openrouter=XXX

# Local config:
