# Models based on https://aider.chat/docs/leaderboards/ at 2025-04-15
alias:
  # few free that actually works
  - "r:openrouter/microsoft/mai-ds-r1:free"
  # Via Openrouter.ai
  - "q0:openrouter/qwen/qwen3-coder-30b-a3b-instruct" # USD 0.25
  - "q1:openrouter/qwen/qwen3-coder" # USD 0.95
  - "d0:openrouter/deepseek/deepseek-v3.2-exp" # USD 0.4
  - "d1:openrouter/deepseek/deepseek-r1-0528" # USD 1.75
  - "a0:openrouter/openai/gpt-5-mini" # USD 2
  - "a1:openrouter/openai/gpt-5" # USD 10
  - "g0:openrouter/google/gemini-2.5-flash" # USD 2.5
  - "g1:openrouter/google/gemini-2.5-pro" # USD 10-15
  - "x0:openrouter/x-ai/grok-code-fast-1" # USD 1.5
  - "x1:openrouter/x-ai/grok-4" # USD 15
  - "c0:openrouter/anthropic/claude-3.5-haiku" # USD 4
  - "c1:openrouter/anthropic/claude-sonnet-4.5" # USD 15
  # Google
  - "gg:gemini/gemma-3-27b-it" # free
  - "gg0:gemini/gemini-flash-latest" # USD 2.5
  - "gg1:gemini/gemini-pro-latest" # USD 10-15
  # Google Copilot with OpenAI compatibility
  - "gh0:openai/gpt-5-mini" # free for paid plans
  - "gh1:openai/gpt-5" # 1x "premium request"

# Default model (possibly alias):
model: r

# Other global life quality settings:
vim: true
dark-mode: true
watch-files: true
analytics-disable: true

# Configure API key(s) here, if not set in environment variables:
#api-key:
#  - openrouter=XXX
#  - gemini=XXX

# Local config:
