# Models based on https://aider.chat/docs/leaderboards/ at 2025-04-15
alias:
  # few free that actually works
  - "r:openrouter/x-ai/grok-4-fast:free"
  #- "free:openrouter/deepseek/deepseek-chat:free"
  # Google Gemini
  - "g:gemini/gemma-3-27b-it" # free
  - "gfl:gemini/gemini-2.5-flash-lite" # USD 0.4
  - "gf:gemini/gemini-2.5-flash" # USD 2.5
  - "gp:gemini/gemini-2.5-pro" # USD 10-15
  # Openrouter
  - "rg:openrouter/google/gemma-3-27b-it" # USD 0.2
  - "qwen:openrouter/qwen/qwen3-coder" # USD 0.3
  - "llama:openrouter/meta-llama/llama-4-maverick" # USD 0.6
  - "deepseek:openrouter/deepseek/deepseek-chat-v3.1" # USD 1.5
  - "grok:openrouter/x-ai/grok-code-fast-1" # USD 1.5
  - "devstral:openrouter/mistralai/devstral-medium" # USD 2.0
  - "rgf:openrouter/google/gemini-2.5-flash" # USD 2.5
  - "c3:openrouter/anthropic/claude-3.5-haiku" # USD 4
  - "o3m:openrouter/openai/o3-mini-high" # USD 4.40
  - "o4m:openrouter/openai/o4-mini-high" # USD 4.40
  - "gpt5:openrouter/openai/gpt-5" # USD 5
  - "rgp:openrouter/google/gemini-2.5-pro" # USD 10-15
  - "rgpp:openrouter/google/gemini-2.5-pro-preview" # USD 10-15
  - "c4:openrouter/anthropic/claude-sonnet-4" # USD 15

# Default model (possibly alias):
model: free

# Other global life quality settings:
vim: true
dark-mode: true
watch-files: true
analytics-disable: true

# Configure API key(s) here, if not set in environment variables:
#api-key:
#  - openrouter=XXX
#  - gemini=XXX

# Local config:
