# Models based on https://aider.chat/docs/leaderboards/ at 2025-04-15
alias:
  - "free:openrouter/mistralai/mistral-7b-instruct:free" # the only free that actually works
  - "ds:openrouter/deepseek/deepseek-chat-v3-0324" # $1.5
  - "o3m:openrouter/openai/o3-mini-high" # $4.40
  - "o4m:openrouter/openai/o4-mini-high" # $4.40
  - "gi:openrouter/google/gemini-2.5-pro-preview-03-25" # $10-15
  - "cl:openrouter/anthropic/claude-3.7-sonnet" # $15

# Default model (possibly alias):
model: free

# Other global life quality settings:
vim: true
dark-mode: true
watch-files: true
analytics-disable: true

# Configure API key(s) here:
api-key:
  - openrouter=XXX

# Local config:
