#!/bin/bash
# Ensure .config directory
mkdir -p ~/.config

# Softlink all the files
mysoftlink .vimrc ~/.vimrc
mysoftlink .vim ~/.vim
mysoftlink .vim ~/.config/nvim
mysoftlink .screenrc ~/.screenrc
mysoftlink .bashrc ~/.bashrc
mysoftlink .tmux.conf ~/.tmux.conf
mysoftlink .gitconfig ~/.gitconfig
mysoftlink .Xmodmap ~/.Xmodmap
mysoftlink .tigrc ~/.tigrc
mysoftlink .psqlrc ~/.psqlrc
mysoftlink .inputrc ~/.inputrc
mysoftlink .bunfig.toml ~/.bunfig.toml
mysoftlink .npmrc ~/.npmrc
mysoftlink .yarnrc.yml ~/.yarnrc.yml
mysoftlink .ansible.cfg ~/.ansible.cfg
mysoftlink .config/opencode ~/.config/opencode
mysoftlink .config/Code ~/.config/Code
mysoftlink .config/ghostty ~/.config/ghostty
mysoftlink .config/uv ~/.config/uv

# Damn you Microsoft for not being able to keep everything in one place
if [[ "$OSTYPE" == "darwin"* ]]; then
	# For system-level install
	mysoftlink .config/Code "$HOME/Library/Application Support/Code"
	# For portable (which I prefer)
	mysoftlink .config/Code "$HOME/Applications/code-portable-data"
fi
