#!/bin/bash
# Ensure .config directory
mkdir -p ~/.config

# Most important ones to link
mysoftlink .vimrc ~/.vimrc
mysoftlink .vim ~/.vim
mysoftlink .bashrc ~/.bashrc
mysoftlink .tmux.conf ~/.tmux.conf
mysoftlink .tigrc ~/.tigrc

# Do NOT link these on Omarchy, because "opinionated"...
if [[ "$ID" != "omarchy" ]]; then
	# Softlink the remaining ones
	mysoftlink .vim ~/.config/nvim
	mysoftlink .screenrc ~/.screenrc
	mysoftlink .gitconfig ~/.gitconfig
	mysoftlink .Xmodmap ~/.Xmodmap
	mysoftlink .config/ghostty ~/.config/ghostty
	mysoftlink .psqlrc ~/.psqlrc
	mysoftlink .inputrc ~/.inputrc
	mysoftlink .bunfig.toml ~/.bunfig.toml
	mysoftlink .npmrc ~/.npmrc
	mysoftlink .yarnrc.yml ~/.yarnrc.yml
	mysoftlink .ansible.cfg ~/.ansible.cfg
	mysoftlink .config/opencode ~/.config/opencode
	mysoftlink .config/Code ~/.config/Code
	mysoftlink .config/uv ~/.config/uv
fi

# Damn you Microsoft for not being able to keep everything in one place
if [[ "$OSTYPE" == "darwin"* ]]; then
	# For system-level install
	mysoftlink .config/Code "$HOME/Library/Application Support/Code"
	# For portable (which I prefer)
	mysoftlink .config/Code "$HOME/Applications/code-portable-data"
fi
